### PR TITLE
Update storage account implementation

### PR DESCRIPTION
**Pull request by garrytrinder**
Merging this PR will 

- Update db-setup.js script
  - Connection string can now be passed to the script, if no string is passed it assumes local development connection string
  - `--reset` flag added to delete, create and populate tables
  - Tables are skipped if already exist when not using `--reset` flag, each table is checked
- Add a task to ensure database tables and data are present on F5 for local development
- `npm install` task has been moved from `teamsapp.local.yml` file to `.vscode/tasks.json`
  - This is so we can run `npm install` before starting azurite and not break the first run experience, i.e. npm install > start azurite > ensure database
- Update environment variable `TABLE_STORAGE_CONNECTION_STRING` to `SECRET_STORAGE_ACCOUNT_CONNECTION_STRING`
  - A connection string applies to Blob, File, Table and Queues, so the name reflects its real usage
  - This moves the environment variable to the `env.<env>.user` file where it is now encrypted
  - `config.tableStorageConnectionString` is now `config.storageAccountConnectionString`
- Update `azure.bicep` with table storage provisioning
  -  `STORAGE_ACCOUNT_CONNECTION_STRING` web app setting is set to Azure resource connection string
  -  Connection string from Azure is written to `SECRET_STORAGE_ACCOUNT_CONNECTION_STRING` environment variable in `env.dev.user`
- Add `env.local.sample.user` file
- Update `resourceBaseName` value in `azure.parameters.json`
  - Was set to `ME`, changed to `me` as storage accounts can only have lowercase letters
- Updates readme
  - Removes redundant manual db setup tasks
  - Adds `db-setup.js` script usage for resetting local and remote table storage

### CODE REVIEW

**Comment by rabwill** [comment]
@garrytrinder testing now :) thanks so much!!

**Comment by rabwill** [comment]
@garrytrinder works great! Just need some additional things in read me (not urgent at all and this branch can be merged @BobGerman )

- add instruction on how to decrypt `SECRET_STORAGE_ACCOUNT_CONNECTION_STRING` using teams toolkit 
- update instruction for setting up Azure tables as someone would do it the very first time after provision/deploy and then mention how they can reset with the -reset flag later.

**Comment by garrytrinder** [comment]
I've updated the readme with instructions on to decrypt the connection string value and improved the instructions for running the db-script.js file to reset local and remote databases.

I've not added instructions on how to setup the database for the first time as this is performed during the first F5 run, so requires no manual work from the developer.

**Review by BobGerman — APPROVED** [review]
This is awesome - works great and so powerful - thanks!

**Pull request merged**
